language: node_js
node_js:
  - 8.10.0

cache:
  directories:
  - node_modules

before_install:
  - npm -g install yarn@^1.7.0
  - yarn add codecov.io coveralls

script:
  - yarn test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - yarn build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: demo/dist
    on:
      branch: master
      condition: $TRAVIS_PULL_REQUEST = false

  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      branch: master
      condition: $TRAVIS_PULL_REQUEST = false

branches:
  only:
    - master

notifications:
  email:
    - raphael.morineau@gmail.com
    - maximilian.pichler97@gmail.com
    - huber.tarik@gmail.com